[package]
name = "rust_experiments"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.4"
typed-arena = "2.0.2"

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "quick_select"
harness = false
